#!/bin/sh
set -e

case "$1" in
  remove|purge)
    if command -v update-desktop-database >/dev/null 2>&1; then
      update-desktop-database /usr/share/applications
    fi
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
      gtk-update-icon-cache -f /usr/share/icons/hicolor
    fi
    ;;
esac

exit 0
